package com.tnevada.model.bc;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 29 14:49:20 ART 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OriginacionViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdCamp,
        Documento,
        Apellido,
        Nombre,
        TipoDocumento,
        Sexo,
        FechaNacimiento,
        CondLaboral,
        Provincia,
        Sucursal,
        Telefono1,
        Telefono2,
        Telefono3,
        Telefono4;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDCAMP = AttributesEnum.IdCamp.index();
    public static final int DOCUMENTO = AttributesEnum.Documento.index();
    public static final int APELLIDO = AttributesEnum.Apellido.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int TIPODOCUMENTO = AttributesEnum.TipoDocumento.index();
    public static final int SEXO = AttributesEnum.Sexo.index();
    public static final int FECHANACIMIENTO = AttributesEnum.FechaNacimiento.index();
    public static final int CONDLABORAL = AttributesEnum.CondLaboral.index();
    public static final int PROVINCIA = AttributesEnum.Provincia.index();
    public static final int SUCURSAL = AttributesEnum.Sucursal.index();
    public static final int TELEFONO1 = AttributesEnum.Telefono1.index();
    public static final int TELEFONO2 = AttributesEnum.Telefono2.index();
    public static final int TELEFONO3 = AttributesEnum.Telefono3.index();
    public static final int TELEFONO4 = AttributesEnum.Telefono4.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OriginacionViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute IdCamp.
     * @return the IdCamp
     */
    public Long getIdCamp() {
        return (Long)getAttributeInternal(IDCAMP);
    }

    /**
     * Gets the attribute value for the calculated attribute Documento.
     * @return the Documento
     */
    public Long getDocumento() {
        return (Long)getAttributeInternal(DOCUMENTO);
    }

    /**
     * Gets the attribute value for the calculated attribute Apellido.
     * @return the Apellido
     */
    public String getApellido() {
        return (String)getAttributeInternal(APELLIDO);
    }

    /**
     * Gets the attribute value for the calculated attribute Nombre.
     * @return the Nombre
     */
    public String getNombre() {
        return (String)getAttributeInternal(NOMBRE);
    }

    /**
     * Gets the attribute value for the calculated attribute TipoDocumento.
     * @return the TipoDocumento
     */
    public String getTipoDocumento() {
        return (String)getAttributeInternal(TIPODOCUMENTO);
    }

    /**
     * Gets the attribute value for the calculated attribute Sexo.
     * @return the Sexo
     */
    public String getSexo() {
        return (String)getAttributeInternal(SEXO);
    }

    /**
     * Gets the attribute value for the calculated attribute FechaNacimiento.
     * @return the FechaNacimiento
     */
    public Timestamp getFechaNacimiento() {
        return (Timestamp)getAttributeInternal(FECHANACIMIENTO);
    }

    /**
     * Gets the attribute value for the calculated attribute CondLaboral.
     * @return the CondLaboral
     */
    public String getCondLaboral() {
        return (String)getAttributeInternal(CONDLABORAL);
    }

    /**
     * Gets the attribute value for the calculated attribute Provincia.
     * @return the Provincia
     */
    public String getProvincia() {
        return (String)getAttributeInternal(PROVINCIA);
    }

    /**
     * Gets the attribute value for the calculated attribute Sucursal.
     * @return the Sucursal
     */
    public String getSucursal() {
        return (String)getAttributeInternal(SUCURSAL);
    }

    /**
     * Gets the attribute value for the calculated attribute Telefono1.
     * @return the Telefono1
     */
    public Long getTelefono1() {
        return (Long)getAttributeInternal(TELEFONO1);
    }

    /**
     * Gets the attribute value for the calculated attribute Telefono2.
     * @return the Telefono2
     */
    public Long getTelefono2() {
        return (Long)getAttributeInternal(TELEFONO2);
    }

    /**
     * Gets the attribute value for the calculated attribute Telefono3.
     * @return the Telefono3
     */
    public Long getTelefono3() {
        return (Long)getAttributeInternal(TELEFONO3);
    }

    /**
     * Gets the attribute value for the calculated attribute Telefono4.
     * @return the Telefono4
     */
    public Long getTelefono4() {
        return (Long)getAttributeInternal(TELEFONO4);
    }
}

