package com.tnevada.model.bc;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 29 14:49:20 ART 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OriginacionViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OriginacionViewImpl() {
    }

    /**
     * Returns the variable value for camp.
     * @return variable value for camp
     */
    public Long getcamp() {
        return (Long)ensureVariableManager().getVariableValue("camp");
    }

    /**
     * Sets <code>value</code> for variable camp.
     * @param value value to bind as camp
     */
    public void setcamp(Long value) {
        ensureVariableManager().setVariableValue("camp", value);
    }
}

