
package com.oracle.xmlns.autorizarcompra;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "AutorizarCompra", targetNamespace = "http://xmlns.oracle.com/AutorizarCompra",
                  wsdlLocation =
                  "http://adf10-desa01.tarjetanevada.com.ar:7780/orabpel/default/AutorizarCompra/1.4?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FAutorizarCompra%7DAutorizarCompra")
public class AutorizarCompra_Service extends Service {

    private final static URL AUTORIZARCOMPRA_WSDL_LOCATION;
    private final static WebServiceException AUTORIZARCOMPRA_EXCEPTION;
    private final static QName AUTORIZARCOMPRA_QNAME =
        new QName("http://xmlns.oracle.com/AutorizarCompra", "AutorizarCompra");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://adf10-desa01.tarjetanevada.com.ar:7780/orabpel/default/AutorizarCompra/1.4?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FAutorizarCompra%7DAutorizarCompra");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTORIZARCOMPRA_WSDL_LOCATION = url;
        AUTORIZARCOMPRA_EXCEPTION = e;
    }

    public AutorizarCompra_Service() {
        super(__getWsdlLocation(), AUTORIZARCOMPRA_QNAME);
    }

    public AutorizarCompra_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTORIZARCOMPRA_QNAME, features);
    }

    public AutorizarCompra_Service(URL wsdlLocation) {
        super(wsdlLocation, AUTORIZARCOMPRA_QNAME);
    }

    public AutorizarCompra_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTORIZARCOMPRA_QNAME, features);
    }

    public AutorizarCompra_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutorizarCompra_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AutorizarCompra
     */
    @WebEndpoint(name = "AutorizarCompraPort")
    public AutorizarCompra getAutorizarCompraPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/AutorizarCompra", "AutorizarCompraPort"),
                             AutorizarCompra.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutorizarCompra
     */
    @WebEndpoint(name = "AutorizarCompraPort")
    public AutorizarCompra getAutorizarCompraPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/AutorizarCompra", "AutorizarCompraPort"),
                             AutorizarCompra.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTORIZARCOMPRA_EXCEPTION != null) {
            throw AUTORIZARCOMPRA_EXCEPTION;
        }
        return AUTORIZARCOMPRA_WSDL_LOCATION;
    }

}
