
package com.oracle.xmlns.autorizarcompra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "AutorizarCompra", targetNamespace = "http://xmlns.oracle.com/AutorizarCompra")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface AutorizarCompra {


    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.autorizarcompra.AutorizarCompraProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "AutorizarCompraProcessResponse", targetNamespace = "http://xmlns.oracle.com/AutorizarCompra",
               partName = "payload")
    public AutorizarCompraProcessResponse process(@WebParam(name = "AutorizarCompraProcessRequest",
                                                            targetNamespace = "http://xmlns.oracle.com/AutorizarCompra",
                                                            partName = "payload")
                                                  AutorizarCompraProcessRequest payload);

}
