package com.oracle.xmlns.autorizarcompra;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1008
public class AutorizarCompraPortClient {
    public static void main(String[] args) {
        AutorizarCompra_Service autorizarCompra_Service = new AutorizarCompra_Service();



    }
}
