package consultamensaje.consultas.backing.view;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1008
public class MensajesWSSoap12HttpPortClient {
    public static void main(String[] args) {
        MensajesWS_Service mensajesWS_Service = new MensajesWS_Service();
        MensajesWS mensajesWS = mensajesWS_Service.getMensajesWSSoap12HttpPort();
        // Add your code to call the desired methods.


    }
}
