
package consultamensaje.consultas.backing.view;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "MensajesWS", targetNamespace = "http://view.backing.consultas.consultaMensaje/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
            com.oracle.webservices.internal.literal.ObjectFactory.class,
            consultamensaje.consultas.backing.view.ObjectFactory.class,
            consultamensaje.consultas.backing.view.types.ObjectFactory.class
    })
public interface MensajesWS {


    /**
     *
     * @param parameters
     * @return
     *     returns consultamensaje.consultas.backing.view.AddMensajeResponseElement
     */
    @WebMethod(action = "http://view.backing.consultas.consultaMensaje//addMensaje")
    @WebResult(name = "addMensajeResponseElement", targetNamespace = "http://view.backing.consultas.consultaMensaje/",
               partName = "parameters")
    public AddMensajeResponseElement addMensaje(@WebParam(name = "addMensajeElement",
                                                          targetNamespace =
                                                          "http://view.backing.consultas.consultaMensaje/",
                                                          partName = "parameters") AddMensajeElement parameters);

    /**
     *
     * @param parameters
     * @return
     *     returns consultamensaje.consultas.backing.view.GetMensajesResponseElement
     */
    @WebMethod(action = "http://view.backing.consultas.consultaMensaje//getMensajes")
    @WebResult(name = "getMensajesResponseElement", targetNamespace = "http://view.backing.consultas.consultaMensaje/",
               partName = "parameters")
    public GetMensajesResponseElement getMensajes(@WebParam(name = "getMensajesElement",
                                                            targetNamespace =
                                                            "http://view.backing.consultas.consultaMensaje/",
                                                            partName = "parameters") GetMensajesElement parameters);

}
