package model.session;

public interface Constantes {
    public static final int ESTADO_LOGIN_ACEPTADO = 1, ESTADO_LOGIN_DESAUTORIZADO = 2, PAGO_EXITOSO = 3, PAGO_INVALIDO =
        4, VERIFICACION_DE_OPERACION_EXITOSA = 5, VERIFICACION_DE_OPERACION_INCORRECTA =
        6, COMERCIO_INEXISTENTE_EN_LA_RELACION = 99;
}
